### PR TITLE
Adds a Lot of Commands

### PR DESCRIPTION
**Pull request by WeegeeVenom**
As stated in the readme, I added 2 new commands.
The first allows you to directly test the program off Sublime. It only allows Python for now.
The second is Download. It allows you to write the name of the exercise name and track name from Sublime's text drop and will download it. I haven't tested for all tracks but it should work. It's neither case- nor space-sensitive (e.g. "  Hello     World  " will be converted to "hello-world")

I feel these two additions will help in being able to do a lot of the commands for exercism without needing to switch to command prompt or powershell as often.

### CODE REVIEW

**Comment by WeegeeVenom** [comment]
I keep making changes so I'll just wait till I actually stop updating this every other hour

**Comment by thosgood** [comment]
this looks nice — thanks for working on this! I'm looking forward to seeing it done :-)

**Comment by WeegeeVenom** [comment]
> 
> 
> this looks nice — thanks for working on this! I'm looking forward to seeing it done :-)

Thank you! I found the original plugin to be quite useful, which led to this rabbit hole of writing a buncha commands for the sake of making it even more convenient (and for personal amusement/learning). In the end, I wanted to share this with you and anyone who wanted to check it out. I learned a lot about python and making plugins for Sublime through working on this.

**Comment by WeegeeVenom** [comment]
I've finally finished what I've mostly wanted to work on for this plugin. I'll still be around if there's any issues of course but currently I don't think I can add much else. I hope you appreciate the changes I've made

**Comment by thosgood** [comment]
I'll test this out later on and then merge it, thank you so much!

**Pull request merged**
